### ISSUE TITLE
Doubt regarding modifications to word substitution approach

### ISSUE THREAD

**Issue by RishabhMaheshwary** [robinjia/certified-word-sub#1]
In the paper it is written that :

"the adversary applies substitutions one at a time, and the neighborhoods and language model scores are computed relative to the current altered version of the input. This results in a hard-to-define attack surface, as changing one word can allow or disallow changes to other words"

What do you mean by "hard-to-define attack surface as changing one word can allow or disallow changes to other words" statement ?

Thanks !

**Comment by robinjia** [comment]
This is describing the Alzantot et al. paper https://arxiv.org/pdf/1804.07998.pdf At a high level, the difference is that our approach specifies up front what the possible perturbations are for each sentence. In Alzantot et al., the possibilities are defined through a local search through the space of perturbations. This makes the set of possible perturbations they consider very hard to define formally, and also seems to allow more drift because the adversary could change the same word multiple times.
